build:
  version: "2.0"

cards:
  message: "Welcome to  cards related QA APIs "
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@cards-apis.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371