build:
  version: "1.0"

loans:
  message: "Welcome to  loans related Prod APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "aishwarya@loans-apis.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384